import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient, HttpResponse } from '@angular/common/http';

import { map } from 'rxjs/operators';


@Injectable()
export class CourseService {
    constructor(private readonly http: HttpClient) {}

    ROOT_URL = '/api/v1/courses/1';

    loadActivities(): Observable<HttpResponse<Course>> {
        console.log('loadActivity')
        return this.http.get<Course>(this.ROOT_URL, { observe: 'response' });
    }

    loadCourses() {
        console.log('loadCourses')
        return this.http.get<any[]>(this.ROOT_URL).pipe(
            map((response: any) => response.courses)
        );
    }

    createCourses() {
        console.log('createCourses')
        return this.http.get<any[]>(this.ROOT_URL).pipe(
            map((response: any) => response.courses)
        );
    }
}

export interface Courses {
    name: string;
    id: number;
    activities: any[];
}

export interface Course {
    name: string;
    id: number;
    activities: any[];
}

// Generated by https://quicktype.io

export interface Course2 {
    name:         string;
    desc:         string;
    sandbox_name: string;
}
